// <auto-generated />
using AstrologyApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstrologyApi.Migrations
{
    [DbContext(typeof(AstrologyApiContext))]
    [Migration("20240227174521_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AstrologyApi.Models.Sign", b =>
                {
                    b.Property<int>("SignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Concentration")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Expression")
                        .HasColumnType("longtext");

                    b.Property<string>("SignName")
                        .HasColumnType("longtext");

                    b.HasKey("SignId");

                    b.ToTable("Signs");
                });
#pragma warning restore 612, 618
        }
    }
}
